import './forms/formInputsConstraints/nameInput.js'
import './forms/formInputsConstraints/id_phone_numberInputs.js'
import './forms/formInputsConstraints/emailInput.js'
import './forms/formInputsConstraints/websiteInput.js'
import './forms/formInputsConstraints/dateInput.js'
import './forms/formInputsConstraints/avatarInput.js'